---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Приложение должно иметь адаптивную верстку
  - Приложение должно иметь поле вход и поле регистрация пользователя, чтобы проводить авторизацию
  

Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. НФ
Сайт должен быть безопасным и защищать данные пользователя. НФ
Пользователь должен иметь возможность искать товары по ключевому слову или категории. Ф
Пользователь должен иметь возможность фильтровать товары Ф
Сайт должен иметь мобильную версию. Ф
Сайт должен быть протестирован на совместимость с последними версиями браузеров.НФ
Сайт должен быть способен обрабатывать большое количество трафика НФ
Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре Ф
Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины Ф
Сайт должен быть доступен на различных устройствах НФ
